.TH "bayesnet::Network" 3 "Version 1.0.5" "BayesNet" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bayesnet::Network
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNetwork\fP (float)"
.br
.ti -1c
.RI "\fBNetwork\fP (const \fBNetwork\fP &)"
.br
.ti -1c
.RI "torch::Tensor & \fBgetSamples\fP ()"
.br
.ti -1c
.RI "float \fBgetMaxThreads\fP () const"
.br
.ti -1c
.RI "void \fBaddNode\fP (const std::string &)"
.br
.ti -1c
.RI "void \fBaddEdge\fP (const std::string &, const std::string &)"
.br
.ti -1c
.RI "std::map< std::string, std::unique_ptr< \fBNode\fP > > & \fBgetNodes\fP ()"
.br
.ti -1c
.RI "std::vector< std::string > \fBgetFeatures\fP () const"
.br
.ti -1c
.RI "int \fBgetStates\fP () const"
.br
.ti -1c
.RI "std::vector< std::pair< std::string, std::string > > \fBgetEdges\fP () const"
.br
.ti -1c
.RI "int \fBgetNumEdges\fP () const"
.br
.ti -1c
.RI "int \fBgetClassNumStates\fP () const"
.br
.ti -1c
.RI "std::string \fBgetClassName\fP () const"
.br
.ti -1c
.RI "void \fBfit\fP (const std::vector< std::vector< int > > &input_data, const std::vector< int > &labels, const std::vector< double > &weights, const std::vector< std::string > &featureNames, const std::string &className, const std::map< std::string, std::vector< int > > &states)"
.br
.ti -1c
.RI "void \fBfit\fP (const torch::Tensor &X, const torch::Tensor &y, const torch::Tensor &weights, const std::vector< std::string > &featureNames, const std::string &className, const std::map< std::string, std::vector< int > > &states)"
.br
.ti -1c
.RI "void \fBfit\fP (const torch::Tensor &samples, const torch::Tensor &weights, const std::vector< std::string > &featureNames, const std::string &className, const std::map< std::string, std::vector< int > > &states)"
.br
.ti -1c
.RI "std::vector< int > \fBpredict\fP (const std::vector< std::vector< int > > &)"
.br
.ti -1c
.RI "torch::Tensor \fBpredict\fP (const torch::Tensor &)"
.br
.ti -1c
.RI "torch::Tensor \fBpredict_tensor\fP (const torch::Tensor &samples, const bool proba)"
.br
.ti -1c
.RI "std::vector< std::vector< double > > \fBpredict_proba\fP (const std::vector< std::vector< int > > &)"
.br
.ti -1c
.RI "torch::Tensor \fBpredict_proba\fP (const torch::Tensor &)"
.br
.ti -1c
.RI "double \fBscore\fP (const std::vector< std::vector< int > > &, const std::vector< int > &)"
.br
.ti -1c
.RI "std::vector< std::string > \fBtopological_sort\fP ()"
.br
.ti -1c
.RI "std::vector< std::string > \fBshow\fP () const"
.br
.ti -1c
.RI "std::vector< std::string > \fBgraph\fP (const std::string &title) const"
.br
.ti -1c
.RI "void \fBinitialize\fP ()"
.br
.ti -1c
.RI "std::string \fBdump_cpt\fP () const"
.br
.ti -1c
.RI "std::string \fBversion\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB15\fP of file \fBNetwork\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "bayesnet::Network::Network ()"

.PP
Definition at line \fB13\fP of file \fBNetwork\&.cc\fP\&.
.SS "bayesnet::Network::Network (float maxT)\fR [explicit]\fP"

.PP
Definition at line \fB16\fP of file \fBNetwork\&.cc\fP\&.
.SS "bayesnet::Network::Network (const \fBNetwork\fP & other)\fR [explicit]\fP"

.PP
Definition at line \fB20\fP of file \fBNetwork\&.cc\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void bayesnet::Network::addEdge (const std::string & parent, const std::string & child)"

.PP
Definition at line \fB95\fP of file \fBNetwork\&.cc\fP\&.
.SS "void bayesnet::Network::addNode (const std::string & name)"

.PP
Definition at line \fB46\fP of file \fBNetwork\&.cc\fP\&.
.SS "std::string bayesnet::Network::dump_cpt () const"

.PP
Definition at line \fB420\fP of file \fBNetwork\&.cc\fP\&.
.SS "void bayesnet::Network::fit (const std::vector< std::vector< int > > & input_data, const std::vector< int > & labels, const std::vector< double > & weights, const std::vector< std::string > & featureNames, const std::string & className, const std::map< std::string, std::vector< int > > & states)"

.PP
Definition at line \fB177\fP of file \fBNetwork\&.cc\fP\&.
.SS "void bayesnet::Network::fit (const torch::Tensor & samples, const torch::Tensor & weights, const std::vector< std::string > & featureNames, const std::string & className, const std::map< std::string, std::vector< int > > & states)"

.PP
Definition at line \fB169\fP of file \fBNetwork\&.cc\fP\&.
.SS "void bayesnet::Network::fit (const torch::Tensor & X, const torch::Tensor & y, const torch::Tensor & weights, const std::vector< std::string > & featureNames, const std::string & className, const std::map< std::string, std::vector< int > > & states)"

.PP
Definition at line \fB158\fP of file \fBNetwork\&.cc\fP\&.
.SS "std::string bayesnet::Network::getClassName () const"

.PP
Definition at line \fB75\fP of file \fBNetwork\&.cc\fP\&.
.SS "int bayesnet::Network::getClassNumStates () const"

.PP
Definition at line \fB63\fP of file \fBNetwork\&.cc\fP\&.
.SS "std::vector< std::pair< std::string, std::string > > bayesnet::Network::getEdges () const"

.PP
Definition at line \fB371\fP of file \fBNetwork\&.cc\fP\&.
.SS "std::vector< std::string > bayesnet::Network::getFeatures () const"

.PP
Definition at line \fB59\fP of file \fBNetwork\&.cc\fP\&.
.SS "float bayesnet::Network::getMaxThreads () const"

.PP
Definition at line \fB38\fP of file \fBNetwork\&.cc\fP\&.
.SS "std::map< std::string, std::unique_ptr< \fBNode\fP > > & bayesnet::Network::getNodes ()"

.PP
Definition at line \fB116\fP of file \fBNetwork\&.cc\fP\&.
.SS "int bayesnet::Network::getNumEdges () const"

.PP
Definition at line \fB383\fP of file \fBNetwork\&.cc\fP\&.
.SS "torch::Tensor & bayesnet::Network::getSamples ()"

.PP
Definition at line \fB42\fP of file \fBNetwork\&.cc\fP\&.
.SS "int bayesnet::Network::getStates () const"

.PP
Definition at line \fB67\fP of file \fBNetwork\&.cc\fP\&.
.SS "std::vector< std::string > bayesnet::Network::graph (const std::string & title) const"

.PP
Definition at line \fB357\fP of file \fBNetwork\&.cc\fP\&.
.SS "void bayesnet::Network::initialize ()"

.PP
Definition at line \fB29\fP of file \fBNetwork\&.cc\fP\&.
.SS "std::vector< int > bayesnet::Network::predict (const std::vector< std::vector< int > > & tsamples)"

.PP
Definition at line \fB237\fP of file \fBNetwork\&.cc\fP\&.
.SS "torch::Tensor bayesnet::Network::predict (const torch::Tensor & samples)"

.PP
Definition at line \fB230\fP of file \fBNetwork\&.cc\fP\&.
.SS "std::vector< std::vector< double > > bayesnet::Network::predict_proba (const std::vector< std::vector< int > > & tsamples)"

.PP
Definition at line \fB259\fP of file \fBNetwork\&.cc\fP\&.
.SS "torch::Tensor bayesnet::Network::predict_proba (const torch::Tensor & samples)"

.PP
Definition at line \fB224\fP of file \fBNetwork\&.cc\fP\&.
.SS "torch::Tensor bayesnet::Network::predict_tensor (const torch::Tensor & samples, const bool proba)"

.PP
Definition at line \fB205\fP of file \fBNetwork\&.cc\fP\&.
.SS "double bayesnet::Network::score (const std::vector< std::vector< int > > & tsamples, const std::vector< int > & labels)"

.PP
Definition at line \fB275\fP of file \fBNetwork\&.cc\fP\&.
.SS "std::vector< std::string > bayesnet::Network::show () const"

.PP
Definition at line \fB344\fP of file \fBNetwork\&.cc\fP\&.
.SS "std::vector< std::string > bayesnet::Network::topological_sort ()"

.PP
Definition at line \fB387\fP of file \fBNetwork\&.cc\fP\&.
.SS "std::string bayesnet::Network::version ()\fR [inline]\fP"

.PP
Definition at line \fB49\fP of file \fBNetwork\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BayesNet from the source code\&.
