.TH "bayesnet::BaseClassifier" 3 "Version 1.0.5" "BayesNet" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bayesnet::BaseClassifier
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBbayesnet::Classifier\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fBBaseClassifier\fP & \fBfit\fP (std::vector< std::vector< int > > &X, std::vector< int > &y, const std::vector< std::string > &features, const std::string &className, std::map< std::string, std::vector< int > > &states)=0"
.br
.ti -1c
.RI "virtual \fBBaseClassifier\fP & \fBfit\fP (torch::Tensor &X, torch::Tensor &y, const std::vector< std::string > &features, const std::string &className, std::map< std::string, std::vector< int > > &states)=0"
.br
.ti -1c
.RI "virtual \fBBaseClassifier\fP & \fBfit\fP (torch::Tensor &dataset, const std::vector< std::string > &features, const std::string &className, std::map< std::string, std::vector< int > > &states)=0"
.br
.ti -1c
.RI "virtual \fBBaseClassifier\fP & \fBfit\fP (torch::Tensor &dataset, const std::vector< std::string > &features, const std::string &className, std::map< std::string, std::vector< int > > &states, const torch::Tensor &weights)=0"
.br
.ti -1c
.RI "virtual torch::Tensor \fBpredict\fP (torch::Tensor &X)=0"
.br
.ti -1c
.RI "virtual std::vector< int > \fBpredict\fP (std::vector< std::vector< int > > &X)=0"
.br
.ti -1c
.RI "virtual torch::Tensor \fBpredict_proba\fP (torch::Tensor &X)=0"
.br
.ti -1c
.RI "virtual std::vector< std::vector< double > > \fBpredict_proba\fP (std::vector< std::vector< int > > &X)=0"
.br
.ti -1c
.RI "virtual status_t \fBgetStatus\fP () const =0"
.br
.ti -1c
.RI "virtual float \fBscore\fP (std::vector< std::vector< int > > &X, std::vector< int > &y)=0"
.br
.ti -1c
.RI "virtual float \fBscore\fP (torch::Tensor &X, torch::Tensor &y)=0"
.br
.ti -1c
.RI "virtual int \fBgetNumberOfNodes\fP () const =0"
.br
.ti -1c
.RI "virtual int \fBgetNumberOfEdges\fP () const =0"
.br
.ti -1c
.RI "virtual int \fBgetNumberOfStates\fP () const =0"
.br
.ti -1c
.RI "virtual int \fBgetClassNumStates\fP () const =0"
.br
.ti -1c
.RI "virtual std::vector< std::string > \fBshow\fP () const =0"
.br
.ti -1c
.RI "virtual std::vector< std::string > \fBgraph\fP (const std::string &title='') const =0"
.br
.ti -1c
.RI "virtual std::string \fBgetVersion\fP ()=0"
.br
.ti -1c
.RI "virtual std::vector< std::string > \fBtopological_order\fP ()=0"
.br
.ti -1c
.RI "virtual std::vector< std::string > \fBgetNotes\fP () const =0"
.br
.ti -1c
.RI "virtual std::string \fBdump_cpt\fP () const =0"
.br
.ti -1c
.RI "virtual void \fBsetHyperparameters\fP (const nlohmann::json &hyperparameters)=0"
.br
.ti -1c
.RI "std::vector< std::string > & \fBgetValidHyperparameters\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBtrainModel\fP (const torch::Tensor &weights)=0"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "std::vector< std::string > \fBvalidHyperparameters\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB13\fP of file \fBBaseClassifier\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "std::vector< std::string > & bayesnet::BaseClassifier::getValidHyperparameters ()\fR [inline]\fP"

.PP
Definition at line \fB40\fP of file \fBBaseClassifier\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "std::vector<std::string> bayesnet::BaseClassifier::validHyperparameters\fR [protected]\fP"

.PP
Definition at line \fB43\fP of file \fBBaseClassifier\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BayesNet from the source code\&.
