.TH "bayesnet::Proposal" 3 "Version 1.0.5" "BayesNet" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bayesnet::Proposal
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBbayesnet::AODELd\fP, \fBbayesnet::KDBLd\fP, \fBbayesnet::SPODELd\fP, and \fBbayesnet::TANLd\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBProposal\fP (torch::Tensor &pDataset, std::vector< std::string > &features_, std::string &className_)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBcheckInput\fP (const torch::Tensor &X, const torch::Tensor &y)"
.br
.ti -1c
.RI "torch::Tensor \fBprepareX\fP (torch::Tensor &X)"
.br
.ti -1c
.RI "map< std::string, std::vector< int > > \fBlocalDiscretizationProposal\fP (const map< std::string, std::vector< int > > &states, \fBNetwork\fP &model)"
.br
.ti -1c
.RI "map< std::string, std::vector< int > > \fBfit_local_discretization\fP (const torch::Tensor &y)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "torch::Tensor \fBXf\fP"
.br
.ti -1c
.RI "torch::Tensor \fBy\fP"
.br
.ti -1c
.RI "map< std::string, mdlp::CPPFImdlp * > \fBdiscretizers\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB17\fP of file \fBProposal\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "bayesnet::Proposal::Proposal (torch::Tensor & pDataset, std::vector< std::string > & features_, std::string & className_)"

.PP
Definition at line \fB10\fP of file \fBProposal\&.cc\fP\&.
.SS "bayesnet::Proposal::~Proposal ()\fR [virtual]\fP"

.PP
Definition at line \fB11\fP of file \fBProposal\&.cc\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void bayesnet::Proposal::checkInput (const torch::Tensor & X, const torch::Tensor & y)\fR [protected]\fP"

.PP
Definition at line \fB17\fP of file \fBProposal\&.cc\fP\&.
.SS "map< std::string, std::vector< int > > bayesnet::Proposal::fit_local_discretization (const torch::Tensor & y)\fR [protected]\fP"

.PP
Definition at line \fB77\fP of file \fBProposal\&.cc\fP\&.
.SS "map< std::string, std::vector< int > > bayesnet::Proposal::localDiscretizationProposal (const map< std::string, std::vector< int > > & states, \fBNetwork\fP & model)\fR [protected]\fP"

.PP
Definition at line \fB26\fP of file \fBProposal\&.cc\fP\&.
.SS "torch::Tensor bayesnet::Proposal::prepareX (torch::Tensor & X)\fR [protected]\fP"

.PP
Definition at line \fB104\fP of file \fBProposal\&.cc\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "map<std::string, mdlp::CPPFImdlp*> bayesnet::Proposal::discretizers\fR [protected]\fP"

.PP
Definition at line \fB28\fP of file \fBProposal\&.h\fP\&.
.SS "torch::Tensor bayesnet::Proposal::Xf\fR [protected]\fP"

.PP
Definition at line \fB26\fP of file \fBProposal\&.h\fP\&.
.SS "torch::Tensor bayesnet::Proposal::y\fR [protected]\fP"

.PP
Definition at line \fB27\fP of file \fBProposal\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BayesNet from the source code\&.
